
export const materias = {
    primaria: [
      "Matemáticas",
      "Lenguaje y Literatura",
      "Ciencias Naturales",
      "Ciencias Sociales",
      "Educación Física",
      "Arte",
      "Música",
      "Inglés",
      "Computación",
      "Formación Ética y Ciudadana",
      "Educación Cívica",
      "Educación Ambiental",
      "Educación Vial",
      "Educación Sexual Integral",
      "Historia",
      "Geografía",
    ],
    secundaria: [
      "Matemáticas",
      "Lengua y Literatura",
      "Biología",
      "Física",
      "Química",
      "Historia",
      "Geografía",
      "Filosofía",
      "Sociología",
      "Economía",
      "Educación Física",
      "Arte",
      "Música",
      "Inglés",
      "Computación",
      "Educación Ciudadana",
      "Educación Ambiental",
      "Educación Sexual Integral",
      "Psicología",
    ],
    universidad: [
      "Cálculo",
      "Álgebra Lineal",
      "Estadística",
      "Física",
      "Química",
      "Biología",
      "Programación",
      "Bases de Datos",
      "Inteligencia Artificial",
      "Sistemas Operativos",
      "Redes de Computadoras",
      "Diseño de Interfaz",
      "Economía",
      "Contabilidad",
      "Marketing",
      "Finanzas",
      "Psicología",
      "Sociología",
      "Filosofía",
      "Historia",
    ],
  };



