/*
export  const materias = [
  "Matemáticas",
  "Lenguaje y Literatura",
  "Ciencias Naturales",
  "Ciencias Sociales",
  "Educación Física",
  "Arte",
  "Música",
  "Inglés",
  "Computación",
  "Formación Ética y Ciudadana",
  "Educación Cívica",
  "Educación Ambiental",
  "Educación Vial",
  "Educación Sexual Integral",
  "Historia",
  "Geografía",
  "Biología",
  "Física",
  "Química",
  "Filosofía",
  "Sociología",
  "Economía",
  "Psicología",
  "Cálculo",
  "Álgebra Lineal",
  "Estadística",
  "Programación",
  "Bases de Datos",
  "Inteligencia Artificial",
  "Sistemas Operativos",
  "Redes de Computadoras",
  "Diseño de Interfaz",
  "Contabilidad",
  "Marketing",
  "Finanzas"
]
*/


export const materias = {
    primaria: [
      "Matematicas",
      "Lenguaje y Literatura",
      "Ciencias Naturales",
      "Ciencias Sociales",
      "Educación Física",
      "Arte",
      "Musica",
      "Inglés",
      "Computación",
      "Formación Etica y Ciudadana",
      "Educación Cívica",
      "Educación Ambiental",
      "Educación Vial",
      "Educación Sexual Integral",
      "Historia",
      "Geografia",
    ],
    secundaria: [
      "Matematicas",
      "Lengua y Literatura",
      "Biología",
      "Fisica",
      "Quimica",
      "Historia",
      "Geografía",
      "Filosofía",
      "Sociología",
      "Economia",
      "Educacion Fisica",
      "Arte",
      "Musica",
      "Ingles",
      "Computacion",
      "Educación Ciudadana",
      "Educación Ambiental",
      "Educación Sexual Integral",
      "Psicologia",
    ],
    universidad: [
      "Calculo",
      "Álgebra Lineal",
      "Estadística",
      "Fisica",
      "Quimica",
      "Biología",
      "Programación",
      "Bases de Datos",
      "Inteligencia Artificial",
      "Sistemas Operativos",
      "Redes de Computadoras",
      "Diseño de Interfaz",
      "Economía",
      "Contabilidad",
      "Marketing",
      "Finanzas",
      "Psicología",
      "Sociología",
      "Filosofía",
      "Historia",
    ],
  };



